### ISSUE TITLE
Bad Link on 'Getting Started' page

### ISSUE THREAD

**Issue by dallastexas92** [RedisLabs/redislabs-docs#1284] opened 2021-03-22 15:15 UTC
**Current behavior** (A short description of what you found)
This link doesn't take you anywhere (hyperlinked under step 3 of 'To Install RS run...':

https://docs.redislabs.com/latest/rs/installing-upgrading/#custom-installation-directories

**Expected behavior** (A short description of what you expected to find)
Link should open up with custom directories

**Screenshots** (Paste or drag-and-drop a screenshot)
![image](https://user-images.githubusercontent.com/33672687/112012470-38d57300-8af7-11eb-9a50-99643edef4ee.png)

**Additional context** (Add any other information)

**Comment by dallastexas92** [comment] 2021-03-22 15:15
Highlighted link above is the link in question

**Comment by lanceleonard** [comment] 2021-04-26 17:06
This behavior is actually as designed; the link target points to the section header containing the process.  (When the header is already in view, nothing seems to happen.)

Removed the link and reordered the step contents.  This should provide a better experience.

**Comment by lanceleonard** [comment] 2021-05-03 18:18
It looks like we've resolved this issue, so I'm closing this.

**Closed by lanceleonard** 2021-05-03 18:18 UTC
